### ISSUE TITLE
use language toolkit to improve conversation flow

### ISSUE THREAD

**Issue by LoganParker** [edouarde1/310-Group-Project#6]
Implement **at least** three of:
- [x] Part-of-speech tagging 
- [x] Named entity recognition
- [ ] Phrasal
- [ ] Coreference resolution
- [ ] Sentiment analysis
- [ ] Synonym recognition

**Comment by LoganParker** [comment]
Tentatively also doing synonym detection

**Comment by wasmiester** [comment]
done
